### ISSUE TITLE
Resource not found: mailTrigger

### ISSUE THREAD

**Issue by RaynorD** [Spencer-Easton/Apps-Script-Gmail-Push-Notifications-v2#1]
I get this when I run my setupPubSub(). I'm sure it's something I did wrong, but I've quadruple checked that I followed the guide correctly and done everything I can think of without access to your library code. Any idea what would cause this?

Error: { "error": { "code": 404, "message": "Resource not found (resource=mailTrigger).", "status": "NOT_FOUND" } } (line 32, file "PubsubApp", project "PubSubApp")

**Comment by Spencer-Easton** [comment]
What a bad error message (which comes from the api not me)! The issue is that when you add the webapp url to the verified domain list in the dev console you need to omit the "exec" from the end.  I added that to the README.  Thanks for letting me know.
